# Generated by Django 4.1.11 on 2023-10-01 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_alter_author_name_alter_condition_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='books', to='books.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='interested_users',
            field=models.ManyToManyField(blank=True, related_name='wanted_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
