# Generated by Django 4.1.11 on 2023-10-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genres_alter_book_interested_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.condition'),
        ),
    ]
